CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  repository_id BIGINT,
  repository_full_name TEXT,
  framework TEXT,
  production_url TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, repository_id)
);

CREATE INDEX IF NOT EXISTS projects_user_created_idx ON projects (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS deployments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  commit_sha TEXT NOT NULL,
  branch TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued',
  duration INTEGER CHECK (duration IS NULL OR duration >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS deployments_user_created_idx ON deployments (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS deployments_project_created_idx ON deployments (project_id, created_at DESC);

CREATE TABLE IF NOT EXISTS activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES projects(id) ON DELETE SET NULL,
  deployment_id BIGINT REFERENCES deployments(id) ON DELETE SET NULL,
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS activity_user_created_idx ON activity (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS activity_project_idx ON activity (project_id);
CREATE INDEX IF NOT EXISTS activity_deployment_idx ON activity (deployment_id);