ALTER TABLE deployments ALTER COLUMN commit_sha DROP NOT NULL;
ALTER TABLE deployments ADD COLUMN IF NOT EXISTS logs TEXT NOT NULL DEFAULT '';
ALTER TABLE deployments ADD COLUMN IF NOT EXISTS deployment_url TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS container_id TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS container_port INTEGER;